# Generated by Django 2.1.4 on 2019-01-03 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MiseqSampleSheetSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.CharField(max_length=64)),
                ('sample_name', models.CharField(blank=True, max_length=64)),
                ('index_1_i7_seq', models.CharField(blank=True, max_length=16)),
                ('index_2_i5_seq', models.CharField(blank=True, max_length=16)),
                ('irida_project_id', models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='ReadSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_type', models.CharField(blank=True, choices=[('READ_1', 'Read 1'), ('INDEX_1', 'Index 1'), ('INDEX_2', 'Index 2'), ('READ_2', 'Read 2')], max_length=32)),
                ('yield_gigabases', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('error_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
                ('bases_greater_than_q30_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.CharField(max_length=64)),
                ('sample_name', models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='SampleSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(blank=True, max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Sequencer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(blank=True, max_length=256)),
                ('model_name', models.CharField(blank=True, max_length=256)),
                ('sequencer_id', models.CharField(blank=True, max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='SequenceRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='MiseqSampleSheet',
            fields=[
                ('samplesheet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sequdas.SampleSheet')),
                ('iem_file_version', models.CharField(blank=True, max_length=8)),
                ('investigator_name', models.CharField(blank=True, max_length=64)),
                ('project_name', models.CharField(blank=True, max_length=64)),
                ('experiment_name', models.CharField(blank=True, max_length=64)),
                ('date', models.DateField()),
                ('workflow', models.CharField(blank=True, max_length=64)),
                ('assay', models.CharField(blank=True, max_length=64)),
                ('description', models.CharField(blank=True, max_length=64)),
                ('chemistry', models.CharField(blank=True, max_length=64)),
                ('application', models.CharField(blank=True, max_length=64)),
                ('read1_length', models.IntegerField()),
                ('read2_length', models.IntegerField()),
                ('reverse_complement', models.NullBooleanField()),
                ('adapter', models.CharField(blank=True, max_length=128)),
                ('adapter_read2', models.CharField(blank=True, max_length=128)),
            ],
            bases=('sequdas.samplesheet',),
        ),
        migrations.CreateModel(
            name='MiseqSequenceRun',
            fields=[
                ('sequencerun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sequdas.SequenceRun')),
                ('folder', models.CharField(blank=True, max_length=256)),
                ('cluster_density', models.DecimalField(blank=True, decimal_places=2, max_digits=6)),
                ('clusters_passed_filter_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
                ('reads_total', models.PositiveIntegerField(blank=True)),
                ('reads_passed_filter', models.PositiveIntegerField(blank=True)),
                ('bases_greater_than_q30_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
            ],
            bases=('sequdas.sequencerun',),
        ),
        migrations.AddField(
            model_name='sequencerun',
            name='sample_sheet',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sequdas.SampleSheet'),
        ),
        migrations.AddField(
            model_name='sequencerun',
            name='sequencer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sequdas.Sequencer'),
        ),
        migrations.AddField(
            model_name='sample',
            name='sequence_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='sequdas.SequenceRun'),
        ),
        migrations.AddField(
            model_name='readsummary',
            name='sequence_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_summaries', to='sequdas.SequenceRun'),
        ),
        migrations.AddField(
            model_name='miseqsamplesheetsample',
            name='sample_sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sequdas.SampleSheet'),
        ),
    ]
